framework:
    mailer:
        message_bus: false
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@snowtricks.fr'
        headers:
            'X-Auto-Response-Suppress': 'OOF, DR, RN, NRN, AutoReply'