version: '3'
networks:
  default:
    driver: bridge

services:
###> doctrine/doctrine-bundle ###
  mail:
    image: maildev/maildev:2.1.0
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
      MAILDEV_OUTGOING_USER: maileruser
      MAILDEV_OUTGOING_PASS: mailerpassword
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - default
